export const PLACE_ORDER_REUQEST="PLACE_ORDER_REUQEST";
export const ORDER_PLACED="ORDER_PLACED";
export const PLACE_ORDER_FAIL="PLACE_ORDER_FAIL";

export const REQUESTING_ORDERS_PLACED="REQUESTING_ORDERS_PLACED";
export const FETCH_ORDERS_PLACED="FETCH_ORDERS_PLACED";
export const REQUESTING_ORDERS_PLACED_FAIL="REQUESTING_ORDERS_PLACED_FAIL";

export const GET_SPECIFIC_ORDERDATA="GET_SPECIFIC_ORDERDATA";