export const SAVED_PRODUCT_ADD_ITEM_FAIL = 'SAVED_PRODUCT_ADD_ITEM_FAIL';
export const SAVED_PRODUCT_ADD_ITEM = 'SAVED_PRODUCT_ADD_ITEM';
export const SAVED_PRODUCT_REMOVE_ITEM = 'SAVED_PRODUCT_REMOVE_ITEM';
export const INITIALISE_SAVED_PRODUCTS="INITIALISE_SAVED_PRODUCTS";

export const SAVED_STORE_ADD_ITEM_FAIL = 'SAVED_STORE_ADD_ITEM_FAIL';
export const SAVED_STORE_ADD_ITEM = 'SAVED_STORE_ADD_ITEM';
export const SAVED_STORE_REMOVE_ITEM = 'SAVED_STORE_REMOVE_ITEM';
export const INITIALISE_SAVED_STORES="INITIALISE_SAVED_STORES";

export const SAVED_ADDRESS_ADD_ITEM_FAIL = 'SAVED_ADDRESS_ADD_ITEM_FAIL';
export const SAVED_ADDRESS_ADD_ITEM = 'SAVED_ADDRESS_ADD_ITEM';
export const SAVED_ADDRESS_REMOVE_ITEM = 'SAVED_ADDRESS_REMOVE_ITEM';
export const INITIALISE_SAVED_ADDRESS="INITIALISE_SAVED_ADDRESS";

export const SELECT_ADDRESS="SELECT_ADDRESS";
export const INITIALISE_SAVED_ADDRESS_KEY="INITIALISE_SAVED_ADDRESS_KEY";

export const SAVED_BLOG_ADD_ITEM_FAIL = 'SAVED_BLOG_ADD_ITEM_FAIL';
export const SAVED_BLOG_ADD_ITEM = 'SAVED_BLOG_ADD_ITEM';
export const SAVED_BLOG_REMOVE_ITEM = 'SAVED_BLOG_REMOVE_ITEM';
export const INITIALISE_SAVED_BLOGS="INITIALISE_SAVED_BLOGS";