export const TOKEN_VALIDITY_CHECK= "TOKEN_VALIDITY_CHECK";
export const TOKEN_VARIFIED= "TOKEN_VARIFIED";
export const TOKEN_VARIFICATION_FAILED= "TOKEN_VARIFICATION_FAILED";

export const REQUESTING_NEW_TOKENS_USING_REFRESHT= "REQUESTING_NEW_TOKENS_USING_REFRESHT";
export const NEW_TOKENS_RECEIVED="NEW_TOKENS_RECEIVED";